-- Insert offices from SEARCH office enrollment.xlsx
-- Generated on 2026-06-18

INSERT INTO `offices` (`name`, `code`, `campus_id`, `head_position_id`, `created_at`, `updated_at`) VALUES
-- ACCESS (campus_id = 1)
('ACCESS - Library', 'acc-lib', 1, 15, NOW(), NOW()),
('ACCESS - Clinic', 'acc-cl', 1, 15, NOW(), NOW()),
('ACCESS - Guidance Office', 'acc-gui', 1, 15, NOW(), NOW()),
('ACCESS - NSTP Office', 'acc-ns', 1, 15, NOW(), NOW()),
('ACCESS - Socio-Cultural Office', 'acc-sc', 1, 15, NOW(), NOW()),
('ACCESS - Sports Office', 'acc-sp', 1, 15, NOW(), NOW()),
('ACCESS - Supply Office', 'acc-sup', 1, 15, NOW(), NOW()),
('ACCESS - GAD Office', 'acc-gad', 1, 15, NOW(), NOW()),
('ACCESS - SBO Office', 'acc-sbo', 1, 15, NOW(), NOW()),
('ACCESS - Research Office', 'acc-res', 1, 15, NOW(), NOW()),
('ACCESS - Extension Office', 'acc-ext', 1, 15, NOW(), NOW()),
('ACCESS - Accreditation Office', 'acc-acr', 1, 15, NOW(), NOW()),
('ACCESS - Production Office', 'acc-prd', 1, 15, NOW(), NOW()),

-- Bagumbayan (campus_id = 7)
('Bagumbayan - Library', 'bag-lib', 7, 15, NOW(), NOW()),
('Bagumbayan - Clinic', 'bag-cl', 7, 15, NOW(), NOW()),
('Bagumbayan - Guidance Office', 'bag-gui', 7, 15, NOW(), NOW()),
('Bagumbayan - NSTP Office', 'bag-ns', 7, 15, NOW(), NOW()),
('Bagumbayan - Socio-Cultural Office', 'bag-sc', 7, 15, NOW(), NOW()),
('Bagumbayan - Sports Office', 'bag-sp', 7, 15, NOW(), NOW()),
('Bagumbayan - Supply Office', 'bag-sup', 7, 15, NOW(), NOW()),
('Bagumbayan - GAD Office', 'bag-gad', 7, 15, NOW(), NOW()),
('Bagumbayan - SBO Office', 'bag-sbo', 7, 15, NOW(), NOW()),
('Bagumbayan - Research Office', 'bag-res', 7, 15, NOW(), NOW()),
('Bagumbayan - Extension Office', 'bag-ext', 7, 15, NOW(), NOW()),
('Bagumbayan - Accreditation Office', 'bag-acr', 7, 15, NOW(), NOW()),
('Bagumbayan - Production Office', 'bag-prd', 7, 15, NOW(), NOW()),

-- Isulan (campus_id = 3)
('Isulan - Library', 'isu-lib', 3, 15, NOW(), NOW()),
('Isulan - Clinic', 'isu-cl', 3, 15, NOW(), NOW()),
('Isulan - Guidance Office', 'isu-gui', 3, 15, NOW(), NOW()),
('Isulan - NSTP Office', 'isu-ns', 3, 15, NOW(), NOW()),
('Isulan - Socio-Cultural Office', 'isu-sc', 3, 15, NOW(), NOW()),
('Isulan - Sports Office', 'isu-sp', 3, 15, NOW(), NOW()),
('Isulan - Supply Office', 'isu-sup', 3, 15, NOW(), NOW()),
('Isulan - GAD Office', 'isu-gad', 3, 15, NOW(), NOW()),
('Isulan - SBO Office', 'isu-sbo', 3, 15, NOW(), NOW()),
('Isulan - Research Office', 'isu-res', 3, 15, NOW(), NOW()),
('Isulan - Extension Office', 'isu-ext', 3, 15, NOW(), NOW()),
('Isulan - Accreditation Office', 'isu-acr', 3, 15, NOW(), NOW()),
('Isulan - Production Office', 'isu-prd', 3, 15, NOW(), NOW()),

-- Kalamansig (campus_id = 4)
('Kalamansig - Library', 'kal-lib', 4, 15, NOW(), NOW()),
('Kalamansig - Clinic', 'kal-cl', 4, 15, NOW(), NOW()),
('Kalamansig - Guidance Office', 'kal-gui', 4, 15, NOW(), NOW()),
('Kalamansig - NSTP Office', 'kal-ns', 4, 15, NOW(), NOW()),
('Kalamansig - Socio-Cultural Office', 'kal-sc', 4, 15, NOW(), NOW()),
('Kalamansig - Sports Office', 'kal-sp', 4, 15, NOW(), NOW()),
('Kalamansig - Supply Office', 'kal-sup', 4, 15, NOW(), NOW()),
('Kalamansig - GAD Office', 'kal-gad', 4, 15, NOW(), NOW()),
('Kalamansig - SBO Office', 'kal-sbo', 4, 15, NOW(), NOW()),
('Kalamansig - Research Office', 'kal-res', 4, 15, NOW(), NOW()),
('Kalamansig - Extension Office', 'kal-ext', 4, 15, NOW(), NOW()),
('Kalamansig - Accreditation Office', 'kal-acr', 4, 15, NOW(), NOW()),
('Kalamansig - Production Office', 'kal-prd', 4, 15, NOW(), NOW()),

-- Lutayan (campus_id = 5)
('Lutayan - Library', 'lut-lib', 5, 15, NOW(), NOW()),
('Lutayan - Clinic', 'lut-cl', 5, 15, NOW(), NOW()),
('Lutayan - Guidance Office', 'lut-gui', 5, 15, NOW(), NOW()),
('Lutayan - NSTP Office', 'lut-ns', 5, 15, NOW(), NOW()),
('Lutayan - Socio-Cultural Office', 'lut-sc', 5, 15, NOW(), NOW()),
('Lutayan - Sports Office', 'lut-sp', 5, 15, NOW(), NOW()),
('Lutayan - Supply Office', 'lut-sup', 5, 15, NOW(), NOW()),
('Lutayan - GAD Office', 'lut-gad', 5, 15, NOW(), NOW()),
('Lutayan - SBO Office', 'lut-sbo', 5, 15, NOW(), NOW()),
('Lutayan - Research Office', 'lut-res', 5, 15, NOW(), NOW()),
('Lutayan - Extension Office', 'lut-ext', 5, 15, NOW(), NOW()),
('Lutayan - Accreditation Office', 'lut-acr', 5, 15, NOW(), NOW()),
('Lutayan - Production Office', 'lut-prd', 5, 15, NOW(), NOW()),

-- Palimbang (campus_id = 6)
('Palimbang - Library', 'pal-lib', 6, 15, NOW(), NOW()),
('Palimbang - Clinic', 'pal-cl', 6, 15, NOW(), NOW()),
('Palimbang - Guidance Office', 'pal-gui', 6, 15, NOW(), NOW()),
('Palimbang - NSTP Office', 'pal-ns', 6, 15, NOW(), NOW()),
('Palimbang - Socio-Cultural Office', 'pal-sc', 6, 15, NOW(), NOW()),
('Palimbang - Sports Office', 'pal-sp', 6, 15, NOW(), NOW()),
('Palimbang - Supply Office', 'pal-sup', 6, 15, NOW(), NOW()),
('Palimbang - GAD Office', 'pal-gad', 6, 15, NOW(), NOW()),
('Palimbang - SBO Office', 'pal-sbo', 6, 15, NOW(), NOW()),
('Palimbang - Research Office', 'pal-res', 6, 15, NOW(), NOW()),
('Palimbang - Extension Office', 'pal-ext', 6, 15, NOW(), NOW()),
('Palimbang - Accreditation Office', 'pal-acr', 6, 15, NOW(), NOW()),
('Palimbang - Production Office', 'pal-prd', 6, 15, NOW(), NOW()),

-- Tacurong (campus_id = 2)
('Tacurong - Clinic', 'tac-cl', 2, 15, NOW(), NOW()),
('Tacurong - NSTP Office', 'tac-ns', 2, 15, NOW(), NOW()),
('Tacurong - Socio-Cultural Office', 'tac-sc', 2, 15, NOW(), NOW()),
('Tacurong - Sports Office', 'tac-sp', 2, 15, NOW(), NOW()),
('Tacurong - Supply Office', 'tac-sup', 2, 15, NOW(), NOW()),
('Tacurong - GAD Office', 'tac-gad', 2, 15, NOW(), NOW()),
('Tacurong - SBO Office', 'tac-sbo', 2, 15, NOW(), NOW()),
('Tacurong - Research Office', 'tac-res', 2, 15, NOW(), NOW()),
('Tacurong - Extension Office', 'tac-ext', 2, 15, NOW(), NOW()),
('Tacurong - Accreditation Office', 'tac-acr', 2, 15, NOW(), NOW()),
('Tacurong - Production Office', 'tac-prd', 2, 15, NOW(), NOW());
