-- Insert positions from positions.xlsx
-- Generated on 2026-06-18

INSERT INTO `positions` (`description`, `code`, `created_at`, `updated_at`) VALUES
('COS Faculty', 'cos', NOW(), NOW()),
('Job-Order Staff', 'jo', NOW(), NOW()),
('Project Staff', 'pjs', NOW(), NOW()),
('Administrative Aide I', 'aai1', NOW(), NOW()),
('Administrative Aide II', 'aai2', NOW(), NOW()),
('Administrative Aide III', 'aai3', NOW(), NOW()),
('Administrative Aide IV', 'aai4', NOW(), NOW()),
('Administrative Aide V', 'aai5', NOW(), NOW()),
('Administrative Aide VI', 'aai6', NOW(), NOW()),
('Administrative Assistant I', 'adas1', NOW(), NOW()),
('Administrative Assistant II', 'adas2', NOW(), NOW()),
('Administrative Assistant III', 'adas3', NOW(), NOW()),
('Administrative Assistant IV', 'adas4', NOW(), NOW()),
('Administrative Assistant V', 'adas5', NOW(), NOW()),
('Administrative Assistant VI', 'adas6', NOW(), NOW()),
('Administrative Officer I', 'ao1', NOW(), NOW()),
('Administrative Officer II', 'ao2', NOW(), NOW()),
('Administrative Officer III', 'ao3', NOW(), NOW()),
('Administrative Officer IV', 'ao4', NOW(), NOW()),
('Administrative Officer V', 'ao5', NOW(), NOW()),
('Supervising Administrative Officer', 'sao', NOW(), NOW()),
('Chief Administrative Officer', 'cao', NOW(), NOW()),
('Board Secretary I', 'bs1', NOW(), NOW()),
('Board Secretary V', 'bs5', NOW(), NOW()),
('Human Resource Management Officer I', 'hr1', NOW(), NOW()),
('Human Resource Management Officer II', 'hr2', NOW(), NOW()),
('Human Resource Management Officer III', 'hr3', NOW(), NOW()),
('Information Systems Analyst I', 'isa1', NOW(), NOW()),
('Information Systems Analyst II', 'isa2', NOW(), NOW()),
('Information Technology Officer I', 'ito1', NOW(), NOW()),
('Internal Auditor I', 'ia1', NOW(), NOW()),
('Internal Auditor II', 'ia2', NOW(), NOW()),
('Internal Auditor III', 'ia3', NOW(), NOW()),
('Attorney IV', 'aty4', NOW(), NOW()),
('Legal Assistant II', 'la2', NOW(), NOW()),
('Legal Assistant III', 'la3', NOW(), NOW()),
('Planning Officer I', 'plo1', NOW(), NOW()),
('Planning Officer II', 'plo2', NOW(), NOW()),
('Planning Officer III', 'plo3', NOW(), NOW()),
('Project Development Officer I', 'pdo1', NOW(), NOW()),
('Project Development Officer II', 'pdo2', NOW(), NOW()),
('Project Development Officer III', 'pdo3', NOW(), NOW()),
('Instructor I', 'ins1', NOW(), NOW()),
('Instructor II', 'ins2', NOW(), NOW()),
('Instructor III', 'ins3', NOW(), NOW()),
('Assistant Professor I', 'asi1', NOW(), NOW()),
('Assistant Professor II', 'asi2', NOW(), NOW()),
('Assistant Professor III', 'asi3', NOW(), NOW()),
('Assistant Professor IV', 'asi4', NOW(), NOW()),
('Associate Professor I', 'asso1', NOW(), NOW()),
('Associate Professor II', 'asso2', NOW(), NOW()),
('Associate Professor III', 'asso3', NOW(), NOW()),
('Associate Professor IV', 'asso4', NOW(), NOW()),
('Associate Professor V', 'asso5', NOW(), NOW()),
('Professor I', 'prof1', NOW(), NOW()),
('Professor II', 'prof2', NOW(), NOW()),
('Professor III', 'prof3', NOW(), NOW()),
('Professor IV', 'prof4', NOW(), NOW()),
('Professor V', 'prof5', NOW(), NOW()),
('Professor VI', 'prof6', NOW(), NOW()),
('University Professor', 'uprof', NOW(), NOW());
